name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v3
        
      # 2. 安装Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # 3. 安装依赖并构建
      - name: Install and Build
        run: |
          npm ci
          npm run build
          
      # 4. 配置部署密钥
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      # 5. 推送到Pages仓库
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: your_username/logo-maker-pages
          publish_branch: gh-pages  # Pages服务使用的分支
          publish_dir: ./dist       # 构建输出目录
          keep_files: false         # 完全覆盖目标分支
